### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by TheLTGamer** [VodBox/pyWinContext#2]
There are two things I am having issues with.

1) When I select the option to generate the .reg file and then save, it doesn't generate the .reg file.

2) I used the other option to apply it to windows but now when I try to remux a file or even transcode to a locked 60fps it doesn't do anything. The cmd opens for 0.1seconds and then closes and then nothing happens. I've been waiting for too long for the file and nothing seems to happen.

If you could help out that would be great!

**Comment by VodBox** [comment]
A few things I'll need to be able to understand the specifics of your issue...

1. What version of Windows are you running?
2. Are you trying to run from the source, or are you using the .exe from releases?
3. What is the command that you've put down for remux or transcode?
4. If you add the command "pause" to the line below your command, it should prevent the cmd from closing so you can see any error messages. What does it show you when you do that?

**Comment by TheLTGamer** [comment]
Sorry forgot to close this I had figured it out. I had to set the file destination for ffmpeg.
